services:
  postgres:
    image: postgres:15
    container_name: ai_tutor_db
    environment:
      POSTGRES_USER: aitutor
      POSTGRES_PASSWORD: aitutor_dev_pass
      POSTGRES_DB: ai_tutor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aitutor"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ai_tutor_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://aitutor:aitutor_dev_pass@postgres:5432/ai_tutor
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: